//[202][hotfix] chrissstrahl - added hzm coop mod logo
resource
Widget
{
	name "coop_startServerLogo"
	rect 190 130 256 256
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	shader "textures/mohmenu/coop/hzm_coop_mod_logo"
}

resource
Label
{
	title "1. Select a Mission\n2. Select a Map\n3. Click Apply"
	name "coop_startMapSelect"
	rect 50 200 400 300
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign left
}

resource
Button
{
	title ""
	name "coop_startMap1"
	rect 10 130 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap2"
	rect 136 130 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap3"
	rect 262 130 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap4"
	rect 388 130 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap5"
	rect 514 130 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
//second row
resource
Button
{
	title ""
	name "coop_startMap6"
	rect 10 250 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap7"
	rect 136 250 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap8"
	rect 262 250 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap9"
	rect 388 250 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}
resource
Button
{
	title ""
	name "coop_startMap10"
	rect 514 250 115 115
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.50 0.50 0.50 0.00
	borderstyle "NONE"
	font facfont-20
	textalign center
}

